### ISSUE TITLE
As an unregistered user, I want to be able to register as a user with my chosen credentials (i.e., username and password that are both not empty words) in order to leverage/use services and information that are exclusively available to registered users

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#1]
- [ ] sopra-fs22-group-19/Debatable_Client#1
 
- [ ] sopra-fs22-group-19/Debatable_Client#2

- [ ] sopra-fs22-group-19/Debatable_Client#3

- [x] sopra-fs22-group-19/Debatable_Client#18

- [ ]  sopra-fs22-group-19/Debatable_Client#17

- [x] #43

- [x] #48

- [x] #69
  
- [x] sopra-fs22-group-19/Debatable_Server#20

- [ ] #49

- [ ] #70

**Comment by chenfeimauzh** [comment]
- [ ] Upon successful user registration, the user is automatically logged in and redirected to the view with the list of available debate topics to join
- [ ] Upon failure, an error is displayed, and the user is redirected (back) to the register screen.
- [ ] A register error can be that a username is already taken.
- [ ] Logged-in users can log out and log back into their registered profile.
