### ISSUE TITLE
If the invitee chooses to register or login, then they should successfully login and be directed to the debate page as a logged in user. 

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#10]
- [x] sopra-fs22-group-19/Debatable_Client#16

- [x] sopra-fs22-group-19/Debatable_Server#60

- [x] sopra-fs22-group-19/Debatable_Server#61 

- [x] sopra-fs22-group-19/Debatable_Server#80
