### ISSUE TITLE
Once the debate officially starts, both the participants should be able to debate one at a time in a given amount of time.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#13]
- [x] #54

- [x] #86

- [x] #55 

- [x] #84

- [x] #58 

- [x] #85

- [x] #59

- [x] #68

- [x] #71

- [x] #72

- [x] #73 

- [x] #78

- [x] sopra-fs22-group-19/Debatable_Client#26

- [x]  sopra-fs22-group-19/Debatable_Client#27

- [x] sopra-fs22-group-19/Debatable_Client#28
