### ISSUE TITLE
As a participant, I want to be able to see a timer in debate room in order to track the remaining time left for posting messages.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#135]
- [x] sopra-fs22-group-19/Debatable_Client#52

- [x] sopra-fs22-group-19/Debatable_Client#53

- [x] sopra-fs22-group-19/Debatable_Client#54

**Comment by JdbermeoUZH** [comment]
closed in PR t [0170e4e](https://github.com/sopra-fs22-group-19/Debatable_Client/commit/0170e4e8f8c64128062ff970bb14d5a54998a48c)
