### ISSUE TITLE
As a participant, I want to be able to end the debate at any time in order to have flexibility in how I use the website and participate in the debates.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#15]
- [x] sopra-fs22-group-19/Debatable_Client#20

- [ ] sopra-fs22-group-19/Debatable_Client#55

- [x] sopra-fs22-group-19/Debatable_Server#62

- [x] sopra-fs22-group-19/Debatable_Server#63

- [x] sopra-fs22-group-19/Debatable_Server#83

- [x] sopra-fs22-group-19/Debatable_Client#29
