### ISSUE TITLE
Finalize for M3 and Bug fix

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#152]
- [x] sopra-fs22-group-19/Debatable_Client#61
- [ ] sopra-fs22-group-19/Debatable_Client#62
- [x] sopra-fs22-group-19/Debatable_Client#63
- [x] sopra-fs22-group-19/Debatable_Client#64
- [x] sopra-fs22-group-19/Debatable_Client#65
- [x] sopra-fs22-group-19/Debatable_Client#66
- [x] sopra-fs22-group-19/Debatable_Client#67
- [ ] sopra-fs22-group-19/Debatable_Client#68
- [x] sopra-fs22-group-19/Debatable_Client#69
- [ ] sopra-fs22-group-19/Debatable_Client#70
- [ ] sopra-fs22-group-19/Debatable_Client#71
- [ ] sopra-fs22-group-19/Debatable_Client#72
- [ ] sopra-fs22-group-19/Debatable_Client#73
- [ ] sopra-fs22-group-19/Debatable_Client#74
