### ISSUE TITLE
as a login in user, i should be able to click on the icon of translation next to the chat box and a translated paragraph of this chat box will appear down below.(External API)

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#16]
- [ ] sopra-fs22-group-19/Debatable_Server#124
- [ ] sopra-fs22-group-19/Debatable_Server#125
- [ ] sopra-fs22-group-19/Debatable_Server#126

- [ ] sopra-fs22-group-19/Debatable_Client#45
- [ ] sopra-fs22-group-19/Debatable_Client#46

**Comment by JdbermeoUZH** [comment]
https://github.com/sopra-fs22-group-19/Debatable_Server/commit/5f34c0052c56ebd44064e88bb8c6dcffa520df4f
