### ISSUE TITLE
Optimize the debate msg code to adapt websocket

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#168]
- [x] sopra-fs22-group-19/Debatable_Server#169

- [x] sopra-fs22-group-19/Debatable_Server#170

- [x] sopra-fs22-group-19/Debatable_Client#79

- [x] sopra-fs22-group-19/Debatable_Client#78

- [x] sopra-fs22-group-19/Debatable_Client#77

- [x] sopra-fs22-group-19/Debatable_Client#76
