### ISSUE TITLE
As a logged-in user,  I want to be able to create a debate topic in order to have more choice.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#17]
- [x] sopra-fs22-group-19/Debatable_Server#129

- [x] sopra-fs22-group-19/Debatable_Server#123

- [x] sopra-fs22-group-19/Debatable_Server#130

- [x] sopra-fs22-group-19/Debatable_Client#47

- [x] sopra-fs22-group-19/Debatable_Client#48

- [x] sopra-fs22-group-19/Debatable_Client#49

- [x] sopra-fs22-group-19/Debatable_Client#50

**Comment by rupalsaxena** [comment]
64e295c129b94f2937dc8b5672d94a4b1791fda0

**Comment by rupalsaxena** [comment]
fc9a333f3ebe41942410d059886941fa37b1ca73
