### ISSUE TITLE
As a logged-in user, I want to be able to see my credentials (i.e. username, name) in a specific tab for this purpose in order for me to see my profile’s information.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#2]
- [x] sopra-fs22-group-19/Debatable_Client#44
 
- [ ] sopra-fs22-group-19/Debatable_Client#4

- [x] sopra-fs22-group-19/Debatable_Client#30

- [x] sopra-fs22-group-19/Debatable_Server#50

- [x] sopra-fs22-group-19/Debatable_Server#51
