### ISSUE TITLE
As a logged-in user, I want to edit my own user profile to set/update my personal information in order to change my profile information as desired, particularly the password.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#3]
- [x] sopra-fs22-group-19/Debatable_Client#6

- [x] sopra-fs22-group-19/Debatable_Server#25

- [x] sopra-fs22-group-19/Debatable_Server#26

- [x] #146
- [x] #147
