### ISSUE TITLE
As a logged-in user, I want to be able to see which debates are available to participate in, as a first participant, in order to know the available debates.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#4]
- [x] sopra-fs22-group-19/Debatable_Client#19

- [x] sopra-fs22-group-19/Debatable_Server#56

- [x] sopra-fs22-group-19/Debatable_Server#57

- [x] #74
