### ISSUE TITLE
As a logged-in user, I want to filter the debates by topic in order to see only the debate topics that are related to my interests.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#5]
- [ ] sopra-fs22-group-19/Debatable_Client#7

- [ ] sopra-fs22-group-19/Debatable_Client#8

- [ ] sopra-fs22-group-19/Debatable_Client#9

- [x] sopra-fs22-group-19/Debatable_Server#30

- [x] sopra-fs22-group-19/Debatable_Server#31

**Comment by oroikono** [comment]
f16c8f303b570011257289e2afe46c6c928b0dff
