### ISSUE TITLE
As a logged-in user, I want to be able to select a debate of my interest and choose the side of the debate in order to debate this topic. By doing so, they will be the first participant of the debate.

### ISSUE THREAD

**Issue by chenfeimauzh** [sopra-fs22-group-19/Debatable_Server#6]
- [x] sopra-fs22-group-19/Debatable_Server#33

- [x] sopra-fs22-group-19/Debatable_Client#10
 
- [x] sopra-fs22-group-19/Debatable_Server#46

- [x] sopra-fs22-group-19/Debatable_Server#47

- [x] #76
